apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - name: event-image 
        image: event-bus
        imagePullPolicy: Never
        ports:
        - containerPort: 4005

---
apiVersion: v1
kind: Service
metadata:
  name: service-event
spec:
  selector:
    app: comment
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
  type: NodePort      