apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deployment
  labels:
    app: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
      - name: comment-image 
        image: comment-image
        imagePullPolicy: Never
        ports:
        - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: service-comment
spec:
  selector:
    app: comment
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: NodePort      