apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
  labels:
    app: moderation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
      - name: moderation-image 
        image: moderation-image
        imagePullPolicy: Never
        ports:
        - containerPort: 4003

---
apiVersion: v1
kind: Service
metadata:
  name: service-moderation
spec:
  selector:
    app: moderation
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003
  type: NodePort      