apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts-images
        image: posts-images
        imagePullPolicy: Never
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: service-posts
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort      